# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    apt install curl
    apt install ruby-full
    apt install sqlite3
    apt install sqlitebrowser
    gem install rails
    
    
  displayName: ' install'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec rake
  displayName: 'bundle exec rake'
